### ISSUE TITLE
Redesign IM selection to depend on locale

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mintlocale#39] opened 2016-06-03 12:03 UTC
Here is what we know so far:
## Korean

uim
uim-byeoru

**Comment by sukso96100** [comment] 2016-06-03 12:40
[nimf](https://github.com/cogniti/nimf) - Supports English, Korean and Chinese Pinyin

**Comment by bagjunggyu** [comment] 2016-06-09 14:56
== Input Method for CJK 
Available in scratch-text-editor is marked (0)
All of them are package name itself need to install themselves

< Korean >
(0) nimf
(0) uim uim-byeoru
(x) fcitx-hangul
(x) ibus-hangul

< Japanese >
nimf is preparing for Japanese based on Anthy and it will be added soon.
https://github.com/cogniti/nimf

(x) ibus-mozc
(x) fcitx-mozc 
(can't test ,nor no need to do in 64-bit) uim uim-mozc:i386
(x) ibus-anthy
(x) fcitx-anthy
(0) uim uim-anthy

< Chinese >
(0) nimf
(0) uim uim-pinyin
(x) fcitx-pinyin
(x) fcitx-sunpinyin
(x) ibus-pinyin
(x) ibus-sunpinyin

Reference]
uim - https://packages.debian.org/sid/uim

Note]
uim is not working in Github.
scratch-text-editor is default text editor of elementary OS 

== Summary
In most cases, uim is good for now in general, but I recommend nimf as a default IM for Asians
Since, this redesigning is planned for Linux Mint 18.1 , nimf would be prepared for CJK about then.
Installing "nimf" would solve all of these issues with Input Method in Chinese, Japanese, Korean at once I think.
It is free from QT5 issue with other GTK issues

ibus
https://code.google.com/p/ibus/issues/detail?id=1726

uim
https://github.com/uim/uim/issues/30

And also, Those are packages for Input Method by locale.

**Comment by fu-sen** [comment] 2016-06-10 05:17
I want to worry about the possibility that the Japanese may be deteriorated.
Currently many Japanese users use the Mozc. Use of Anthy is a minority.
From nimf of the plan, Japanese input environment is clearly worsening.

**Comment by bagjunggyu** [comment] 2016-06-10 05:43
@fu-sen Good to see you again here!
We need your infos about Input Method of Japanese, Can you share your knowledge?
What is Japanese users favorite Input Method? 
Please write down here packages for Japanese Input Method.
And also, Why don't make an issue for nimf developer to change his plan for the Japanse
https://github.com/cogniti/nimf

**Comment by bagjunggyu** [comment] 2016-07-04 13:58
I updated above comment for nimf-anthy which for Japanese.
Since nimf has added its support for Japanese via nimf-anthy just now.
From now on , nimf support for Chinese, Japanese, Korean in one Input Method witnout installing more plugins.

**Comment by fu-sen** [comment] 2016-07-13 04:59
I tried nimf. However, it is difficult to really use.
Probably remains of the now Chinese users and Japan user would not choose this.
nimf will be choices in Korea user, but can not be a complete replacement of Asia user.

**Comment by luyikei** [comment] 2016-07-13 05:29
Could you explain more clearly why it is difficult to use ?

As far as I know, most Japanese users want to Mozc instead of Anthy, so I think we should start developing nimf-mozc. Sorry that I missed this discussion by a month.

**Comment by fu-sen** [comment] 2016-07-13 05:37
@luyikei Thanks to good reaction! This is important in Japanese users.

nimf does not correspond to the conversion of the current Space key.
It is necessary to use the cursor keys.
In addition, Zenkaku/ Hanaku key (全角/半角) does not correspond.
This is a switch key Japanese users that are familiar.
We will need to get to reflect this specification to mmf.

Similarly, Chinese are also likely to need support...

**Comment by luyikei** [comment] 2016-07-13 05:47
You mean, "respond"? I guess fixing the issue is not so hard. Though I should compile the latest version to check if the issue still remains.

**Comment by fu-sen** [comment] 2016-07-13 05:48
Is it can be seen in "Does not support"?

**Comment by luyikei** [comment] 2016-07-13 08:09
I understand it. Just saying.

Anyway, I have to say nimf is not production-ready. It lacks support of Mozc. Also, it lacks an issue tracker but I could have missed it. After all, it has a few developers/contributers, which is the most serious concern for me.

**Comment by bagjunggyu** [comment] 2016-07-13 11:07
I've told it to main nimf developer hodong about most Japanese users use  'mozc', 
and I heard it from him that mozc has as an issue of license , thus he chose 'anthy' instead of 'mozc'.
I agree with 'luykei' to request 'nimf-mozc'  and first I hope you to research license issue of mozc like his concerns about it.

We Asians don't use keyboard layout when typing our characters,
We use Input Method instead.
English or English based keyboard users can choose their keyboard layout in layout
but We didn't have this kind of feature until now before Linux Mint loaded. 
Now , we are gethering here for developing Input Method selection more developed one.

Friends! 
We need more infos of Input Method for Asians, like Vietnamese, and language and characters which even more we don't know still ,but might be used in somewhere else. 
I hope this issue could be spread to more people to make it universial to our Linux World.
and their input method packages to be added to mintlocale-im if it is possible.

and let's talk it more until we can get best option for Asians and the people who need input method like us.
we are starting now.

**Comment by luyikei** [comment] 2016-07-13 11:10
I'd say currently fcitx-mozc is the best choice for Japanese.

**Comment by bagjunggyu** [comment] 2016-07-13 11:21
Oh, fcitx-mozc is the best choice for Japanse, I guessed that it might be uim-mozc though :)
For Korean, actually we don't use fcitx in general , due to its bubble popping up whenever changing layout English between Korean. 
But, yes This is it, we need this real infos about our input method from real users like you and me :)
I am happy to know yours :)

**Comment by luyikei** [comment] 2016-07-13 11:23
It's my pleasure :)

**Comment by luyikei** [comment] 2016-07-13 11:27
I think we should make a README file stating that we need more info to select IMs for each country. Maybe, this link helps :)

**Comment by fu-sen** [comment] 2016-07-13 11:35
uim is default adopted by Debian.
but uim there is a big problem that is not yet fully correspond to the current qt5.
Linux Mint that contains the KDE, will is not suitable to the uim to main.

LMDE has shifted from the Debian user might choose it is glad that there is uim.
Would be choices IBus glad to RedHat user, such as Fedora in the same reason.

Many of Japan Linux users choose the Fcitx. It's most of the factors that can be manipulated in the same way as Windows IME.
Its role is to IBus 1.4 was influential (up to Linux Mint 14), there are circumstances that supposed to be hated by a large change of IBus 1.5.(integration with the GNOME 3)
Therefore Fcitx is maintenance including the Japanese and supported as the substitute

**Comment by bagjunggyu** [comment] 2016-07-13 12:20
@luyikei Good idea :)

ibus issue is still on going  https://code.google.com/archive/p/ibus/issues/1726
it would be resolved in qt5.6, and it was said on Jul 27, 2015 
and now, we are living in the middle of July in 2016.
and it was reported in 2014 after I got message  from Graeme Gott who is developer of Focuswriter
, since  I reported him to have an issue with ibus in Focuswriter which rewrote to qt5 on 2014.

Anyway, now I know that , followed by both of you, fcitx-mozc is the best option for Japanese.
That is great news,  this is it what we wanted to know :)

**Comment by bagjunggyu** [comment] 2016-07-17 03:26
sad news, developer of Nimf said that he will close the PPA , http://cogniti-works.blogspot.kr/2016/07/nimf_16.html
since he as health issue and it makes him unavailable to manage his PPA, but he would develope it continously when he can do.

**Comment by bagjunggyu** [comment] 2016-09-08 20:21
This what I still figured out engines for CJKV and Hindi with fcitx

Chinese )
fcitx-chewing
fcitx-pinyin
fcitx-m17n
fcitx-googlepinyin
fcitx-rime
fcitx-qw

Japanese)
fcitx-mozc (Favorite of Japanese users)
fcitx-anthy

Korean)
fcitx-hangul

Vietnamese)
fcitx-unikey

Hindi)
fcitx-m17n

**Comment by fu-sen** [comment] 2016-09-09 00:05
fcitx-kkc will be added to the Japanese.
It is furnished in advance is ibus-kkc, it has been a standard feature in Fedora.
Therefore, current RedHat distribution has been adopted by the standard.

https://github.com/ueno/libkkc
http://packages.ubuntu.com/yakkety/fcitx-kkc
http://packages.ubuntu.com/yakkety/ibus-kkc

kkc = libkkc - Japanese Kana Kanji conversion library (かな漢字・Kana Kanji)

**Comment by clefebvre** [comment] 2016-10-13 10:28
Hi everyone,

This is what is used by language-selector-gnome:

# File format:
# Column 1: category (tr: translations, fn: fonts, in: input method, wa: writing assistence)
# Column 2: languange code for which the package should only be installed. If empty, install for all languages.
# The language code will be appended in the specified format
# Column 3: dependency package(s). Only install the package in column 4 when this dependency package is already installed.
# Column 4: Package to pull. Can contain language codes at the end if column 2 is empty.
#
# Format: %LCODE%
tr:::language-pack-
tr::gvfs:language-pack-gnome-
# Format: %LCODE% or %LCODE%-%CCODE%
tr::libreoffice-common:libreoffice-l10n-
tr::libreoffice-common:libreoffice-help-
tr::firefox:firefox-locale-
tr::thunderbird:thunderbird-locale-
tr::lightning-extension:lightning-extension-locale-
tr::sunbird:sunbird-locale-
tr::sword-text-gerlut1545:sword-language-pack-
tr::gimp:gimp-help-
tr::evolution:evolution-documentation-
tr::chromium-browser:chromium-browser-l10n
tr::sylpheed:sylpheed-i18n
tr::amarok:amarok-help-
tr::gnome-getting-started-docs:gnome-getting-started-docs-
# Format: %LCODE% or %LCODE%%CCODE% or %LCODE%-%VARIANT%
tr::kdelibs5-data:kde-l10n-
tr::calligra-libs:calligra-l10n-
tr::gcompris:gcompris-sound-

# Finnish support for voikko
wa:fi:firefox:xul-ext-mozvoikko
wa:fi:thunderbird:xul-ext-mozvoikko
wa:fi:seahorse:xul-ext-mozvoikko
wa:fi:epiphany:xul-ext-mozvoikko
wa:fi:libreoffice-core:libreoffice-voikko
wa:fi:ispell:tmispell-voikko
wa:fi::libenchant-voikko
wa:fi::voikko-fi

# LibreOffice support
wa::libreoffice-common:hyphen-
wa::libreoffice-common:mythes-
wa::libreoffice-common:hunspell-
# languages which don't provide a hunspell dictionary yet
wa:eo:libreoffice-common:myspell-eo
wa:et:libreoffice-common:myspell-et
wa:fa:libreoffice-common:myspell-fa
wa:fo:libreoffice-common:myspell-fo
wa:ga:libreoffice-common:myspell-ga
wa:gv:libreoffice-common:myspell-gv
wa:hy:libreoffice-common:myspell-hy
wa:ku:libreoffice-common:myspell-ku
wa:lv:libreoffice-common:myspell-lv
wa:nr:libreoffice-common:myspell-nr
wa:ns:libreoffice-common:myspell-ns
wa:ss:libreoffice-common:myspell-ss
wa:st:libreoffice-common:myspell-st
wa:tn:libreoffice-common:myspell-tn
wa:ts:libreoffice-common:myspell-ts
wa:ve:libreoffice-common:myspell-ve
wa:xh:libreoffice-common:myspell-xh
wa:zu:libreoffice-common:myspell-zu

# Package names not matching the locale
wa:nb:libreoffice-common:hunspell-no
wa:nb:libreoffice-common:hyphen-no
wa:nb:libreoffice-common:mythes-no
wa:nn:libreoffice-common:hunspell-no
wa:nn:libreoffice-common:hyphen-no
wa:nn:libreoffice-common:mythes-no

wa:en:libreoffice-common:openoffice.org-hyphenation
wa:fi:libreoffice-common:openoffice.org-hyphenation
wa:ga:libreoffice-common:openoffice.org-hyphenation
wa:id:libreoffice-common:openoffice.org-hyphenation

# Aspell support for Sylpheed and Abiword
wa::sylpheed:hunspell-
wa::abiword:aspell-
wa::gedit:hunspell-

# poppler-data is useful for CJK
wa::poppler-utils:poppler-data

# word lists
wa:bg::wbulgarian
wa:ca::wcatalan
wa:da::wdanish
wa:de::wngerman
wa:de::wogerman
wa:de::wswiss
wa:en::wamerican
wa:en::wbritish
wa:es::wspanish
wa:fo::wfaroese
wa:fr::wfrench
wa:ga::wirish
wa:ga::wmanx
wa:gl::wgalician-minimos
wa:it::witalian
wa:nb::wnorwegian
wa:nl::wdutch
wa:nn::wnorwegian
wa:pl::wpolish
wa:pt::wportuguese
wa:pt::wbrazilian
wa:sv::wswedish
wa:uk::wukrainian

# fonts
fn:am::fonts-sil-abyssinica
fn:ar::fonts-arabeyes
fn:ar::fonts-kacst
fn:as::fonts-beng
fn:bn::fonts-beng
fn:bo::fonts-tibetan-machine
fn:dz::fonts-tibetan-machine
fn:el::fonts-mgopen
fn:fa::fonts-farsiweb
fn:fa::fonts-sil-scheherazade
fn:gu::fonts-gujr
fn:he::fonts-sil-ezra
fn:hi::fonts-deva
fn:ii::fonts-sil-nuosusil
fn:ja::fonts-takao-mincho
fn:ja::fonts-takao-gothic
fn:km::fonts-khmeros
fn:kn::fonts-knda
fn:ko::fonts-nanum
fn:ko::fonts-nanum-coding
fn:ko::fonts-unfonts-core
fn:lo::fonts-lao
fn:ml::fonts-mlym
fn:mn::fonts-manchufont
fn:mnc::fonts-manchufont
fn:mr::fonts-deva
fn:my::fonts-sil-padauk
fn:ne::fonts-deva
fn:or::fonts-orya
fn:pa::fonts-guru
fn:si::fonts-lklug-sinhala
fn:ta::fonts-taml
fn:te::fonts-telu
fn:th::fonts-thai-tlwg
fn:ug::fonts-ukij-uyghur
fn:ur::fonts-nafees
fn:ur::fonts-sil-scheherazade
fn:yi::fonts-sil-ezra
fn:zh-hans::fonts-noto-cjk
fn:zh-hans::fonts-arphic-uming
fn:zh-hans::fonts-arphic-ukai
fn:zh-hant::fonts-noto-cjk
fn:zh-hant::fonts-arphic-uming
fn:zh-hant::fonts-arphic-ukai

# GhostScript CJK resources
fn:ja:gs-cjk-resource:poppler-data
fn:ja:gs-cjk-resource:fonts-ipafont-mincho
fn:ko:gs-cjk-resource:poppler-data
fn:zh-hans:gs-cjk-resource:poppler-data
fn:zh-hant:gs-cjk-resource:poppler-data

# input method framework
im:ja::fcitx
im:ko::fcitx
im:vi::fcitx
im:zh-hans::fcitx
im:zh-hant::fcitx

# input methods
im:ja:ibus:ibus-mozc
im:ja::fcitx-ui-classic
im:ja::fcitx-frontend-gtk2
im:ja::fcitx-frontend-gtk3
im:ja::fcitx-frontend-qt4
im:ja::fcitx-frontend-qt5
im:ja::fcitx-mozc
im:ja:kio:kde-config-fcitx

im:ko:ibus:ibus-hangul
im:ko::fcitx-ui-classic
im:ko::fcitx-frontend-gtk2
im:ko::fcitx-frontend-gtk3
im:ko::fcitx-frontend-qt4
im:ko::fcitx-frontend-qt5
im:ko::fcitx-hangul
im:ko:kio:kde-config-fcitx

im:te:ibus:ibus-m17n
im:th:ibus:gtk-im-libthai

im:vi:ibus:ibus-unikey
im:vi::fcitx-ui-classic
im:vi::fcitx-frontend-gtk2
im:vi::fcitx-frontend-gtk3
im:vi::fcitx-frontend-qt4
im:vi::fcitx-frontend-qt5
im:vi::fcitx-unikey
im:vi:kio:kde-config-fcitx

im:zh-hans::fcitx-ui-qimpanel
im:zh-hans::fcitx-ui-classic
im:zh-hans::fcitx-frontend-gtk2
im:zh-hans::fcitx-frontend-gtk3
im:zh-hans::fcitx-frontend-qt4
im:zh-hans::fcitx-frontend-qt5
im:zh-hans::fcitx-module-cloudpinyin
im:zh-hans::fcitx-sunpinyin
im:zh-hans::fcitx-pinyin
im:zh-hans::fcitx-table-wubi
im:zh-hans:kio:kde-config-fcitx
im:zh-hans:gnome-shell:ibus-sunpinyin
im:zh-hans:gnome-shell:ibus-table-wubi

im:zh-hant::fcitx-ui-qimpanel
im:zh-hant::fcitx-ui-classic
im:zh-hant::fcitx-frontend-gtk2
im:zh-hant::fcitx-frontend-gtk3
im:zh-hant::fcitx-frontend-qt4
im:zh-hant::fcitx-frontend-qt5
im:zh-hant::fcitx-chewing
im:zh-hant::fcitx-pinyin
im:zh-hant::fcitx-table-cangjie
im:zh-hant:kio:kde-config-fcitx
im:zh-hant:gnome-shell:ibus-chewing
im:zh-hant:gnome-shell:ibus-table-cangjie3
im:zh-hant:gnome-shell:ibus-table-cangjie5
im:zh-hant:gnome-shell:ibus-table-quick-classic

**Comment by clefebvre** [comment] 2016-10-13 10:43
Basically:

fcitx is used for ja, ko, vi and zh.

The following packages are installed as base fcitx support:

fcitx-ui-classic
fcitx-frontend-gtk2
fcitx-frontend-gtk3
fcitx-frontend-qt4
fcitx-frontend-qt5
and kde-config-fcitx (in KDE)

And then:

ja -> fcitx-mozc
ko -> fcitx-hangul
vi -> fcitx-unikey
zh-hans -> fcitx-module-cloudpinyin, fcitx-sunpinyin, fcitx-pinyin, fcitx-table-wubi
zh-hant -> fcitx-chewing, fcitx-pinyin, fcitx-table-cangjie

Nothing is recommended by default for te and th.

**Comment by clefebvre** [comment] 2016-10-14 12:00
The UI is being redesigned to make the IM installation language-centric as opposed to IM-centric.

In other words, you no longer install a particular IM with it, but support for a particular language:

![capture du 2016-10-14 12-59-09](https://cloud.githubusercontent.com/assets/1138515/19386767/039a0ef8-920e-11e6-8074-9ed0b2631e0a.png)

**Comment by clefebvre** [comment] 2016-10-14 12:05
Here are the packages installed for each language:

**zh-hans**
fcitx-module-cloudpinyin
fcitx-pinyin
fcitx-sunpinyin
fcitx-table
fcitx-table-wubi
fonts-arphic-ukai
fonts-arphic-uming
fonts-noto-cjk
ibus-sunpinyin
ibus-table-wubi

**zh-hant**
fcitx-chewing
fcitx-pinyin
fcitx-table-cangjie
fonts-arphic-ukai
fonts-arphic-uming
fonts-noto-cjk
ibus-chewing
ibus-table-cangjie3
ibus-table-cangjie5
ibus-table-quick-classic

**ja**
fcitx-mozc
fonts-ipafont-mincho
fonts-takao-gothic
fonts-takao-mincho
ibus-mozc
mozc-data
mozc-server
mozc-utils-gui
presage

**ko**
fcitx-hangul
fonts-nanum
fonts-nanum-coding
fonts-unfonts-core
ibus-hangul

**vi**
fcitx-unikey
ibus-unikey

**th**
fcitx-table
fcitx-table-thai
fonts-thai-tlwg
gtk-im-libthai
ibus-libthai
ibus-table-thai

**te**
fonts-telu
ibus-m17n

Also, common packages for fcitx and ibus are installed for all languages (except Telugu, which only uses Ibus).

**fcitx**
fcitx
fcitx-config-gtk
fcitx-config-gtk2
fcitx-frontend-all
fcitx-frontend-fbterm
fcitx-frontend-gtk2
fcitx-frontend-gtk3
fcitx-frontend-qt4
fcitx-frontend-qt5
fcitx-keyboard
fcitx-libs
fcitx-libs-gclient
fcitx-libs-qt
fcitx-libs-qt5
fcitx-module-dbus
fcitx-module-kimpanel
fcitx-module-lua
fcitx-module-x11
fcitx-modules
fcitx-tools
fcitx-ui-classic
fcitx-ui-kimpanel
fcitx-ui-light
fcitx-ui-qimpanel
gir1.2-fcitx-1.0
im-config
poppler-data

**ibus**
gir1.2-ibus-1.0
ibus
ibus-clutter
ibus-gtk
ibus-gtk3
ibus-qt4
ibus-table
im-config
poppler-data

**Comment by clefebvre** [comment] 2016-10-14 12:14
https://github.com/linuxmint/mintlocale/commit/cd5b77253cafaf523155b770881799e238c60ade

**Comment by clefebvre** [comment] 2016-10-14 12:16
Please provide as much support as possible:

- about the UI redesign first.
- about the list of packages being installed.

When you do, please explain if anything is missing and why. Don't forget to mention your locale too.

**Comment by fu-sen** [comment] 2016-10-14 12:21
Although ja(Japanese) has been included "presage", this will feel that is wrong...

**Comment by clefebvre** [comment] 2016-10-14 12:24
Here's how to test the latest mintlocale from git.

**Install git**

`apt install git`

**Download the source code**

`git clone https://github.com/linuxmint/mintlocale.git`

**Go in the mintlocale directory**

`cd mintlocale`

**Test it**

`./test`

**Updated it (if new modifications appeared on github)**

If new modifications appeared in github since you last downloaded it, go back to the mintlocale directory, and type the following command to update the source code:

`git pull`

**Keep an eye out for modifications**

You can browse https://github.com/linuxmint/mintlocale/commits/master to see the latest changes.

**Comment by clefebvre** [comment] 2016-10-14 12:24
Hi @fu-sen, you want presage to be removed? why?

**Comment by fu-sen** [comment] 2016-10-14 12:40
@clefebvre I now know presage, and have searched it. In other words, not used.

presage seems to have been used to spell check the English,
If we want to enter the English word, Turn off the Fcitx, and enter it.
Therefore presage does not work.

**Comment by clefebvre** [comment] 2016-10-14 13:15
OK, removed: https://github.com/linuxmint/mintlocale/commit/88f6de03b6b06c8ce922d0c798ef69f2cf18e2f0

**Comment by bagjunggyu** [comment] 2016-10-14 14:28
@clefebvre we need uim uim-byeoru in ko , it should be added to.
and, by the way, it is about font,
We have truly ugly font installed in Sarah, when after removing of fonts-nanum
actually, we love fonts-noto-cjk more, it has good shape
but, after removing of fonts-nanum in order to use fonts-noto-cjk as default font
(Since, Gnome DE call and set fonts-nanum as default font in fontconfig file via installing ibus-hangul,
so it has been heritaged to Mint, but noto-cjk has better shape than nanum)
Sarah doesn't use fonts-noto-cjk as default font when after removing of fonts-nanum, but instead , Sarah use ugly font. 
but I don't have any clue of what font has used instead of fonts-nanum after it has been removed,
can we have fonts-noto-cjk as default font for Mint?

**Comment by clefebvre** [comment] 2016-10-14 15:47
Sarah ships with fonts-noto-cjk installed.

What I can do is change ko from:

```
fcitx-hangul
fonts-nanum
fonts-nanum-coding
fonts-unfonts-core
ibus-hangul
```

to:

```
fcitx-hangul
ibus-hangul
```

That way fonts-nanum will not be installed.

Is that OK?

**Comment by clefebvre** [comment] 2016-10-14 15:49
About UIM, I need to know more info.

Is UIM enough for Korean, or are IBUS/FCITX also needed?

By "enough", I mean: 

- does it work well, with most toolkits..etc.?
- do most Korean people prefer UIM over the other IMs?

**Comment by bagjunggyu** [comment] 2016-10-14 16:04
In some apps, not all IMs are working good, it's up to case by case. 
Thus, we need those 3 IMs (FCITX, IBUS, UIM) indeed.
and 3 of them, UIM is mostly working well in general until Ubuntu 16.04 and Sarah

* Actually we do prefer IBUS , 
However, IBUS's bug has been resolved later of Ubuntu 16.10's packages (as well in Fedora 24) 

And, We do prefer UIM than FCITX as well
 IBUS > UIM > FCITX 

But, now a days, 
NIMF is the best option for us though, nimf is not supported by default in Ubuntu and Debian.
If user would like to install nimf, they need to add Testing-PPA , 
$ sudo apt-add-repository ppa:hodong/testing

or Compile it from Git
https://github.com/cogniti/nimf

but if Linux Mint can support nimf as default, it would be our pleausre :)

**Comment by bagjunggyu** [comment] 2016-10-14 16:15
About Font]
That is the weird thing, after I remove fonts-nanum* and fonts-unfont*.
Sarah does not set fonts-noto-cjk as default font.
Sarah shows ugly font, instead of showing us fonts-noto-cjk by default.
That is weird, and I still don't figure out what font (ugly font) is used instead of fonts-noto-cjk.
Since, there is no font for Korean in Linux Mint unless those fonts (fonts-noto-cjk, fonts-nanum*, fonts-unfonts*)
Anyway, I hope that removing of fonts-nanum* and fonts-unfonts* might work :)

**Comment by fu-sen** [comment] 2016-10-15 01:48
uim is not compatible with qt5 in the current version.
It has impact on the 18 KDE (plasma 5).
It has just been addressed this year:

http://packages.ubuntu.com/search?keywords=uim-qt5
https://packages.debian.org/search?keywords=uim-qt5

**Comment by fu-sen** [comment] 2016-10-15 01:55
Looking back that had a problem of size in the fonts-noto-cjk:
http://segfault.linuxmint.com/2014/11/fonts-noto-cjk/

but Ubuntu flavors will include the fonts-noto-cjk on the desktop of the package.
16.10 There is also a flavor that is included in at ISO:
http://packages.ubuntu.com/xenial/ubuntu-desktop
http://packages.ubuntu.com/xenial/kubuntu-desktop
http://packages.ubuntu.com/xenial/xubuntu-desktop
http://packages.ubuntu.com/xenial/ubuntu-gnome-desktop
http://packages.ubuntu.com/xenial/ubuntu-mate-core

fonts-noto-sans in Japanese is no problem,
but some of the Japanese users will care about the line spacing that vacant.

**Comment by clefebvre** [comment] 2016-10-17 13:27
@bagjunggyu https://github.com/linuxmint/mintlocale/commit/c2a1fb35037fe1254c646964aeefa5f0b2afbc63

**Comment by bagjunggyu** [comment] 2016-10-17 15:07
@clefebvre Thank you Clem :)
It is my pleasure and for us!

**Comment by bagjunggyu** [comment] 2016-10-23 18:54
By the way, I almost forgot it, but, We need "remove" feature for IMs
I think double click of the Install button is good.

**Comment by clefebvre** [comment] 2016-10-31 09:30
I can't really remove, because the languages overlap in terms of packages.

**Comment by bagjunggyu** [comment] 2016-10-31 18:39
OK, I understand it now.
I would explain it to users to use software manager or remove feature of Menu.

**Comment by mxa** [comment] 2016-12-22 09:02
Interesting to see this paradigm shift from "Unless you really need them all, please make sure to install only one input method tool." (quoting 'im-config') to, "let's just install all of the ones supporting this language.

**Comment by bagjunggyu** [comment] 2017-02-22 11:09
Finally I found that ugly font for Korean Hangul appearing when removing 
fonts-nanum, fonts-nanum-coding, fonts-unfonts-core to use noto-cjk as default Korean Hangul font.
It is  fonts-wqy-microhei which is beta now 
* fonts-wqy-microhei : Sans-serif style CJK font derived from Droid
By removing those fonts, Now I can have beautiful noto-sans-cjk as my default font in Serena.
$ apt autoremove fonts-wqy-microhei  fonts-nanum fonts-nanum-coding fonts-unfonts-core

**Comment by mxa** [comment] 2017-02-24 16:07
@bagjunggyu Would you help me getting Korean input to work, somehow I broke it and can't get it to run again. I would be thankful.

**Comment by bagjunggyu** [comment] 2017-02-25 04:53
@mxa Surely I would :)
But I think it would be better to use other channel :) Can you email me? It's in my profile.

**Closed** 2017-08-18 12:28 UTC
