### ISSUE TITLE
LMDE 3: Changing user language and/or region does not work

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/mintlocale#62] opened 2018-10-07 12:08 UTC
Upon choosing another installed language in mintlocale and logout/login one would expect to find the desktop localization changed. In LM 19 it works, but in LMDE 3 it does not. Same behavior for the region setting.
In a multi-user system it should be possible for each user to have his individual language/region, so you would not use the "Apply system-wide" function. "Apply system-wide" works, but language/region change only for the personal folder does not.

**Comment by clefebvre** [comment] 2018-11-28 11:41
Can you reproduce this with another DM than LightDM? Looking into this, it looks like mintlocale is doing its job... it's setting .dmrc and accountservice

**Comment by harlekin777** [comment] 2018-12-08 13:39
Sorry for the late answer. Yes, mintlocale does set .dmrc, but after logout/login the language is not changed anyway. As you proposed, I installed gdm3 and set it as default, but that made my system unbootable. So I cannot answer that question.
One other suggestion: Debian's approach to changing user language is to select it at the login screen, which is imho much more elegant than to select it while logged in, logging out and in again. As you split  mintlocale in two different applications, it might be worth considering to handle the user language selection in the Debian way.

**Comment by clefebvre** [comment] 2019-11-12 17:37
Fixed by https://github.com/linuxmint/mintlocale/commit/5a473ffab8a338bbdd7329459994709c15d8c227.

**Closed by clefebvre** 2019-11-12 17:37 UTC
